tg_bot_token: 123456789qwerty
proxies:
  - URL: socks5h://user:password@192.168.1.1:8080
    countryCode: US
  - URL: socks5h://user:password@192.168.1.1:8080
    countryCode: US
  - URL: socks5h://user:password@192.168.1.1:8080
    countryCode: US